version: "2"

services:

  e2e-runner:
    container_name: e2e-runner
    build: .

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  my-server:
    image: abiosoft/caddy