version: "2"

services:

  testapp:
    container_name: testapp
    build:
      context: .
      dockerfile: Dockerfile

  seleniumapp:
    container_name: seleniumapp
    image: serbanghita/selenium-standalone:latest
    ports:
      - "4444:4444"
