version: "2"

services:

  e2e-runner:
    container_name: e2e-runner
    build: .

  selenium-hub:
    container_name: selenium-hub
    image: elgalu/selenium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false

  selenium-chrome:
    container_name: selenium-chrome
    image: elgalu/selenium
    depends_on:
      - selenium-hub
    ports:
      # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5900
      - 5900:25900
      # noVNC: See what's going on by hitting http://0.0.0.0:6080 in your browser
      #        Important: http://127.0.0.1:6080 works but http://localhost:6080 doesn't
      - 6080:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=false
      - GRID=false
      - CHROME=true
      - FIREFOX=false

  selenium-firefox:
    container_name: selenium-firefox
    image: elgalu/selenium
    depends_on:
      - selenium-hub
    ports:
      # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5901
      - 5901:25900
      # noVNC: See what's going on by hitting http://0.0.0.0:6081 in your browser
      - 6081:26080
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - NOVNC=true
      - SELENIUM_HUB_HOST=selenium-hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - VIDEO=false
      - GRID=false
      - CHROME=false
      - FIREFOX=true

  my-server:
    image: abiosoft/caddy
