version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: start dockers
          command: |
            docker-compose up -d
      - run:
          name: test
          command: |
            docker exec -ti e2e-runner time wget --retry-connrefused --no-check-certificate -T 30  http://localhost:4444 -O /dev/null
            docker exec -e CADDY_SERVER=my-server -ti e2e-runner yarn test
